import { db } from './database'
import { generateId } from '../lib/utils'
import type { User, Incident, MaintenanceTask } from '../types/models'

function daysAgo(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  return d.toISOString()
}

function daysFromNow(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString()
}

const users: User[] = [
  {
    id: generateId(),
    name: 'Carlos Martinez',
    email: 'carlos.martinez@empresa.com',
    phone: '+502 5555-1001',
    role: 'technician',
    status: 'active',
    department: 'IT',
    position: 'Tecnico de Soporte Senior',
    notes: 'Especialista en redes y servidores.',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },
  {
    id: generateId(),
    name: 'Ana Lopez',
    email: 'ana.lopez@empresa.com',
    phone: '+502 5555-1002',
    role: 'technician',
    status: 'active',
    department: 'IT',
    position: 'Tecnico de Infraestructura',
    notes: 'Encargada de cableado estructurado y telecomunicaciones.',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(1),
  },
  {
    id: generateId(),
    name: 'Roberto Giron',
    email: 'roberto.giron@empresa.com',
    phone: '+502 5555-1003',
    role: 'technician',
    status: 'active',
    department: 'IT',
    position: 'Tecnico de Helpdesk',
    notes: 'Atencion de primer nivel y soporte a usuarios finales.',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(3),
  },
]

const incidents: Incident[] = [
  // ── Carlos Martinez ──────────────────────────────
  {
    id: generateId(),
    title: 'Servidor de correo no responde',
    description: 'El servidor de correo Exchange dejo de responder a las 8:00 AM. Los usuarios no pueden enviar ni recibir correos. Se requiere reinicio urgente del servicio.',
    priority: 'critical',
    status: 'open',
    assignee: 'Carlos Martinez',
    reporter: 'Gerencia General',
    location: 'Data Center, Rack 3',
    category: 'IT',
    resolutionNotes: '',
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
    resolvedAt: null,
  },
  {
    id: generateId(),
    title: 'Firewall con reglas desactualizadas',
    description: 'Se detectaron reglas de firewall obsoletas que permiten trafico no autorizado en el puerto 8080. Requiere revision y actualizacion inmediata de las politicas de seguridad.',
    priority: 'high',
    status: 'in-progress',
    assignee: 'Carlos Martinez',
    reporter: 'Auditor de Seguridad',
    location: 'Data Center, Rack 1',
    category: 'IT',
    resolutionNotes: 'Se identificaron 12 reglas obsoletas. En proceso de depuracion.',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
    resolvedAt: null,
  },
  {
    id: generateId(),
    title: 'Backup nocturno fallo 3 noches consecutivas',
    description: 'El job de backup automatico del servidor de base de datos ha fallado las ultimas 3 noches. Error: disco de destino lleno. Se necesita liberar espacio y verificar la programacion.',
    priority: 'high',
    status: 'resolved',
    assignee: 'Carlos Martinez',
    reporter: 'DBA',
    location: 'Data Center, Almacenamiento NAS',
    category: 'IT',
    resolutionNotes: 'Se libero 500GB del NAS eliminando backups antiguos y se reconfiguro la retencion a 30 dias. Backup ejecutado exitosamente.',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
    resolvedAt: daysAgo(3),
  },

  // ── Ana Lopez ────────────────────────────────────
  {
    id: generateId(),
    title: 'Switch de piso 2 con puerto danado',
    description: 'El puerto 14 del switch Cisco del piso 2 no establece enlace. Afecta la conexion de red de 3 estaciones de trabajo en Contabilidad.',
    priority: 'medium',
    status: 'open',
    assignee: 'Ana Lopez',
    reporter: 'Jefe de Contabilidad',
    location: 'Edificio A, Piso 2, Rack de piso',
    category: 'IT',
    resolutionNotes: '',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    resolvedAt: null,
  },
  {
    id: generateId(),
    title: 'Cableado de red desordenado en sala de servidores',
    description: 'El cableado del rack principal esta desorganizado, dificultando la identificacion de conexiones y el mantenimiento. Se requiere re-peinado y etiquetado completo.',
    priority: 'low',
    status: 'in-progress',
    assignee: 'Ana Lopez',
    reporter: 'Jefe de IT',
    location: 'Data Center, Rack 1-4',
    category: 'IT',
    resolutionNotes: 'Se ha completado el rack 1 y 2. Pendiente rack 3 y 4 para manana.',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
    resolvedAt: null,
  },
  {
    id: generateId(),
    title: 'Access Point de sala de reuniones sin senal',
    description: 'El AP Ubiquiti de la sala de reuniones principal no emite senal Wi-Fi. Los usuarios no pueden conectarse durante las presentaciones. LED de estado en ambar.',
    priority: 'high',
    status: 'open',
    assignee: 'Ana Lopez',
    reporter: 'Asistente de Direccion',
    location: 'Edificio A, Piso 3, Sala de Reuniones A',
    category: 'IT',
    resolutionNotes: '',
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
    resolvedAt: null,
  },
  {
    id: generateId(),
    title: 'Instalacion de puntos de red en nueva oficina',
    description: 'Se requiere la instalacion de 8 puntos de red Cat6 en la nueva oficina de Recursos Humanos. Incluye canaleta, patch panel y certificacion.',
    priority: 'medium',
    status: 'resolved',
    assignee: 'Ana Lopez',
    reporter: 'Jefe de RRHH',
    location: 'Edificio B, Piso 1',
    category: 'IT',
    resolutionNotes: '8 puntos instalados, certificados y documentados. Se entrego diagrama actualizado al Jefe de IT.',
    createdAt: daysAgo(15),
    updatedAt: daysAgo(10),
    resolvedAt: daysAgo(10),
  },

  // ── Roberto Giron ────────────────────────────────
  {
    id: generateId(),
    title: 'PC de recepcion no enciende',
    description: 'La computadora de recepcion no enciende al presionar el boton de power. No hay luces en la placa madre. Posible falla de fuente de poder.',
    priority: 'medium',
    status: 'in-progress',
    assignee: 'Roberto Giron',
    reporter: 'Recepcionista',
    location: 'Edificio A, Planta Baja, Recepcion',
    category: 'IT',
    resolutionNotes: 'Se confirmo fuente danada. Se solicito repuesto al proveedor, entrega estimada manana.',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
    resolvedAt: null,
  },
  {
    id: generateId(),
    title: 'Impresora HP de contabilidad atascada constantemente',
    description: 'La impresora HP LaserJet del departamento de Contabilidad se atasca con frecuencia. Ya se limpio el rodillo pero el problema persiste. Posible desgaste del pickup roller.',
    priority: 'low',
    status: 'open',
    assignee: 'Roberto Giron',
    reporter: 'Auxiliar Contable',
    location: 'Edificio A, Piso 2, Contabilidad',
    category: 'IT',
    resolutionNotes: '',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    resolvedAt: null,
  },
  {
    id: generateId(),
    title: 'Usuario no puede acceder a carpeta compartida',
    description: 'El usuario jperez del departamento de Ventas reporta que no puede acceder a la carpeta \\\\servidor\\ventas. Error: "Acceso denegado". Los demas usuarios del departamento si pueden acceder.',
    priority: 'medium',
    status: 'resolved',
    assignee: 'Roberto Giron',
    reporter: 'Juan Perez (Ventas)',
    location: 'Edificio A, Piso 1, Ventas',
    category: 'IT',
    resolutionNotes: 'El usuario habia sido removido del grupo de seguridad "Ventas_RW" en Active Directory. Se re-agrego y se verifico acceso. Problema resuelto.',
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
    resolvedAt: daysAgo(4),
  },
  {
    id: generateId(),
    title: 'Instalacion de Office 365 en 5 equipos nuevos',
    description: 'Llegaron 5 laptops nuevas para el departamento de Marketing. Se requiere configuracion inicial: Windows Update, Office 365, VPN corporativa, antivirus y dominio.',
    priority: 'medium',
    status: 'closed',
    assignee: 'Roberto Giron',
    reporter: 'Jefe de Marketing',
    location: 'Bodega IT',
    category: 'IT',
    resolutionNotes: '5 equipos configurados y entregados. Se creo documento de entrega firmado por cada usuario. Equipos registrados en inventario.',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(8),
    resolvedAt: daysAgo(8),
  },
]

const maintenanceTasks: MaintenanceTask[] = [
  {
    id: generateId(),
    title: 'Actualizacion de firmware en switches',
    description: 'Actualizar firmware de los 6 switches Cisco Catalyst a la version mas reciente. Programar ventana de mantenimiento fuera de horario laboral.',
    responsiblePerson: 'Ana Lopez',
    scheduledDate: daysFromNow(5),
    periodicity: 'quarterly',
    status: 'pending',
    category: 'IT',
    location: 'Data Center + Racks de piso',
    completedDate: null,
    notes: 'Coordinar con Carlos para backup de configuraciones previo a la actualizacion.',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: generateId(),
    title: 'Limpieza de equipos de Data Center',
    description: 'Limpieza fisica de servidores, revision de ventiladores, limpieza de filtros del aire acondicionado de precision y verificacion de temperaturas.',
    responsiblePerson: 'Carlos Martinez',
    scheduledDate: daysFromNow(2),
    periodicity: 'monthly',
    status: 'pending',
    category: 'IT',
    location: 'Data Center',
    completedDate: null,
    notes: '',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: generateId(),
    title: 'Verificacion de backups semanales',
    description: 'Verificar integridad de los backups semanales. Hacer prueba de restauracion de un archivo aleatorio para confirmar que los respaldos son funcionales.',
    responsiblePerson: 'Carlos Martinez',
    scheduledDate: daysFromNow(0),
    periodicity: 'weekly',
    status: 'in-progress',
    category: 'IT',
    location: 'Data Center, NAS',
    completedDate: null,
    notes: 'Restauracion de prueba en curso.',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },
  {
    id: generateId(),
    title: 'Revision de licencias de software',
    description: 'Auditar licencias de Windows, Office 365, antivirus y software especializado. Verificar vencimientos y renovaciones pendientes.',
    responsiblePerson: 'Roberto Giron',
    scheduledDate: daysFromNow(10),
    periodicity: 'quarterly',
    status: 'pending',
    category: 'IT',
    location: 'Oficina IT',
    completedDate: null,
    notes: 'Solicitar reporte de licencias a cada proveedor.',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: generateId(),
    title: 'Mantenimiento preventivo de UPS',
    description: 'Revision del UPS principal del Data Center: prueba de baterias, limpieza de contactos, verificacion de autonomia y test de transferencia.',
    responsiblePerson: 'Carlos Martinez',
    scheduledDate: daysAgo(3),
    periodicity: 'monthly',
    status: 'completed',
    category: 'IT',
    location: 'Data Center',
    completedDate: daysAgo(3),
    notes: 'Baterias al 92% de capacidad. Autonomia: 18 minutos a carga completa. Todo en orden.',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
  },
  {
    id: generateId(),
    title: 'Actualizacion de antivirus en estaciones',
    description: 'Verificar que todas las estaciones de trabajo tengan el agente de antivirus actualizado y reportando correctamente a la consola central.',
    responsiblePerson: 'Roberto Giron',
    scheduledDate: daysAgo(1),
    periodicity: 'monthly',
    status: 'overdue',
    category: 'IT',
    location: 'Todos los pisos',
    completedDate: null,
    notes: '15 de 48 estaciones pendientes de verificacion.',
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
]

export async function seedDatabase() {
  const count = await db.incidents.count()
  if (count > 0) return // ya hay datos

  await db.users.bulkAdd(users)
  await db.incidents.bulkAdd(incidents)
  await db.maintenanceTasks.bulkAdd(maintenanceTasks)

  console.log('Base de datos poblada con datos de ejemplo.')
}
